apiVersion: app/v1
kind: deployment
metadata:
  name: nginx
  labels: 
    app: nginx
    tier: frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      tier: frontend
    template:
      labels:
        app: nginx
        tier: frontend
      spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.imageVersion}}
---
apiVersion:  v1
kind: service
metadata: 
  name: frontend
spec:
  type: {{ .Values.service.type }}
  selector:
    labels:
      app: nginx
      tier: frontend
    ports:
    - name: nginx-svc-ports
      protocol: TCP
      ports: {{ .Values.service.port}}
      targetPort: 80