apiVersion: app/v1
kind: Deployment
metadata:
  name: nginx
  labels: 
    app: nginx
    tier: frontend
spec:
  replicas: {{ .Values.deployment.replicas }}
  selector:
    matchLabels:
      app: nginx
      tier: frontend
    template:
      metadata:
        labels:
          app: nginx
          tier: frontend`
      spec:
      containers:
      - name: nginx
        image: {{ .Values.deployment.imageVersion}}
---
apiVersion:  v1
kind: service
metadata: 
  name: nginx
spec:
  type: {{ .Values.service.type }}
  selector:
      app: nginx
      tier: frontend
  ports:
  - name: nginx-svc-port
    protocol: TCP
    port: {{ .Values.service.port}}
    targetPort: 80