apiVersion: app/v1
kind: Deployment
metadata:
  name: mysql
  namespace: expense
  labels: 
    app:  mysql
    tier: bd
    project: expense
spec:
  replicas: 2
  selector:
    matchLabels:
      app: mysql
      tier: bd
      project: expense
    template:
      metadata:
        labels:
          app: mysql
          tier: bd
          project: expense
      spec:
      containers:
      - name: mysql
        image: raidi/mysql:{{ .Values.deployment.imageVersion}}
---
apiVersion:  v1
kind: Service
metadata: 
  name: mysql
  namespace: expense
spec:
  # type: {{ .Values.service.type }}
  selector:
    app: mysql
    tier: bd
    project: expense
  ports:
  - name: mysql-port
    protocol: TCP
    ports: 3306
    targetPort: 3306